AWSTemplateFormatVersion: "2010-09-09"
Description: ECS cluster
Resources:
  ECSCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: !Sub "${AWS::StackName}"
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-task-execution"
      Path: /
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "ecs-tasks.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                - "ecr:GetAuthorizationToken"
                - "ecr:BatchCheckLayerAvailability"
                - "ecr:GetDownloadUrlForLayer"
                - "ecr:BatchGetImage"
                - "logs:CreateLogGroup"
                - "logs:CreateLogStream"
                - "logs:DescribeLogStreams"
                - "logs:PutLogEvents"
                - "secretsmanager:GetSecretValue"
                - "kms:Decrypt"
                Resource: "*"
Outputs:
  Cluster:
    Description: The Cluster
    Value: !Ref ECSCluster
    Export:
      Name: !Sub "${AWS::StackName}"
  ExecutionRole:
    Description: The Cluster Policy
    Value: !Ref ECSTaskExecutionRole
    Export:
      Name: !Sub "${AWS::StackName}-execution-role"