AWSTemplateFormatVersion: "2010-09-09"
Description: 'VPC Base'
Parameters:
  EnableVPCFlowLogs:
    Description: Create a Flow logs for the VPC.
    AllowedValues:
    - true
    - false
    ConstraintDescription: ''
    Default: true
    Type: String
  VPCCIDR:
    Description: CIDR block for the VPC.
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.10.0.0/16
    Type: String
Conditions:
  CreateVPCFlowLogs:
    Fn::Equals:
    - Ref: EnableVPCFlowLogs
    - true
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock:
        Ref: VPCCIDR
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}
  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId:
        Ref: InternetGateway
      VpcId:
        Ref: VPC
  FlowLogGroup:
    Type: AWS::Logs::LogGroup
    Condition: CreateVPCFlowLogs
    Properties:
      RetentionInDays: 30
  FlowLogsRole:
    Type: AWS::IAM::Role
    Condition: CreateVPCFlowLogs
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - vpc-flow-logs.amazonaws.com
        Version: '2012-10-17'
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - logs:CreateLogStream
            - logs:PutLogEvents
            - logs:DescribeLogGroups
            - logs:DescribeLogStreams
            Effect: Allow
            Resource:
              Fn::GetAtt:
              - FlowLogGroup
              - Arn
          Version: '2012-10-17'
        PolicyName: flowlogs-policy
  FlowLogs:
    Type: AWS::EC2::FlowLog
    Condition: CreateVPCFlowLogs
    Properties:
      DeliverLogsPermissionArn:
        Fn::GetAtt:
        - FlowLogsRole
        - Arn
      LogGroupName:
        Ref: FlowLogGroup
      ResourceId:
        Ref: VPC
      ResourceType: VPC
      TrafficType: ALL
Outputs:
  Vpc:
    Description: The VPC
    Value: !Ref VPC
    Export:
      Name: !Sub "${AWS::StackName}"
  VpcCidr:
    Description: The VPC cidr
    Value: !Ref VPCCIDR
    Export:
      Name: !Sub "${AWS::StackName}-cidr"
  InternetGateway:
    Description: The IGW
    Value: !Ref InternetGateway
    Export:
      Name: !Sub "${AWS::StackName}-igw"