"DbUser" = "N3Xae326CHRgzTL9"
"DbPassword" = "j7wpyFyKGk3H18xJqrphG5Rwh600V8"
"DbName" = "techapp"
"DbPort" = "5432"
"DbHost" = "app.c4jez2letufb.ap-southeast-2.rds.amazonaws.com"
"ListenHost" = "localhost"
"ListenPort" = "3000"